export {
  ConnectionPool,
  connectionPool,
} from './dbConnectionPooling';

export {
  PoolConfig,
  PoolStrategy,
  ConnectionState,
  Connection,
  ConnectionMetrics,
  ConnectionPoolEvents,
  ConnectionAcquisitionOptions,
  QueryResult,
  QueryOptions,
  QueryType,
  Transaction,
  TransactionIsolationLevel,
  HealthCheckResult,
  HealthCheckType,
  QueryOptimizationHint,
  QueryExecutionPlan,
  PreparedStatement,
  CachedQueryResult,
  createPoolConfig,
  createConnectionId,
  createTransactionId,
  createPreparedStatementId,
  createHealthCheckResult,
  createConnection,
  createEmptyMetrics,
  createQueryResult,
  createPreparedStatement,
  isConnectionStale,
  isConnectionHealthy,
  isValidPoolConfig,
  isValidQueryType,
  getQueryTypeFromString,
  calculateQueryCacheKey,
  isTransactionActive,
  isTransactionCompleted,
  getTransactionDuration,
  incrementStatementHitCount,
  isCachedResultExpired,
} from './types';
